/*
	Mock Players data to enter into Players table
	Taken from mockaroo.com
	If any failures on insert, then run:
	delete Players
	select * from Players -- to confirm all rows are deleted
	
	Then retry to insert values into table
*/

insert into Players (FirstName, LastName, Email, StreetAddress, City, StateOrProvince, ZIPcode, PhoneNumber, Position, Number, SchoolYear) values ('Corrie', 'Peevor', 'cpeevor0@e-recht24.de', '13 Hoepker Lane', 'Springfield', 'Illinois', '62711', '217-607-4702', 'D', 98, 'Sr');
insert into Players (FirstName, LastName, Email, StreetAddress, City, StateOrProvince, ZIPcode, PhoneNumber, Position, Number, SchoolYear) values ('Arman', 'Tink', 'atink1@ox.ac.uk', '94 Straubel Park', 'Sacramento', 'California', '94250', '916-349-1467', 'G', 54, 'Sr');
insert into Players (FirstName, LastName, Email, StreetAddress, City, StateOrProvince, ZIPcode, PhoneNumber, Position, Number, SchoolYear) values ('Lion', 'Perton', 'lperton2@hp.com', '89373 Twin Pines Avenue', 'Peoria', 'Illinois', '61640', '309-957-3936', 'C', 86, 'Sr');
insert into Players (FirstName, LastName, Email, StreetAddress, City, StateOrProvince, ZIPcode, PhoneNumber, Position, Number, SchoolYear) values ('Bailey', 'Broadbury', 'bbroadbury3@ow.ly', '029 Lien Junction', 'Aurora', 'Colorado', '80015', '303-270-1170', 'D', 27, 'Fr');
insert into Players (FirstName, LastName, Email, StreetAddress, City, StateOrProvince, ZIPcode, PhoneNumber, Position, Number, SchoolYear) values ('Fraze', 'Stayt', 'fstayt4@vinaora.com', '91 Daystar Park', 'Washington', 'District of Columbia', '20370', '202-541-9545', 'G', 28, 'Sr');
insert into Players (FirstName, LastName, Email, StreetAddress, City, StateOrProvince, ZIPcode, PhoneNumber, Position, Number, SchoolYear) values ('Walton', 'Pettendrich', 'wpettendrich5@netscape.com', '91 Division Circle', 'Harrisburg', 'Pennsylvania', '17110', '717-600-5293', 'C', 57, 'Fr');
insert into Players (FirstName, LastName, Email, StreetAddress, City, StateOrProvince, ZIPcode, PhoneNumber, Position, Number, SchoolYear) values ('Riley', 'Gledhill', 'rgledhill6@booking.com', '3 Eliot Parkway', 'Washington', 'District of Columbia', '20029', '202-560-2841', 'D', 72, 'Fr');
insert into Players (FirstName, LastName, Email, StreetAddress, City, StateOrProvince, ZIPcode, PhoneNumber, Position, Number, SchoolYear) values ('Irvin', 'Havik', 'ihavik7@bravesites.com', '9307 Knutson Street', 'Fresno', 'California', '93762', '559-377-9258', 'RW', 21, 'So');
insert into Players (FirstName, LastName, Email, StreetAddress, City, StateOrProvince, ZIPcode, PhoneNumber, Position, Number, SchoolYear) values ('Wilfred', 'Slopier', 'wslopier8@lulu.com', '69128 Sommers Plaza', 'Irvine', 'California', '92717', '714-310-6110', 'D', 20, 'Jr');
insert into Players (FirstName, LastName, Email, StreetAddress, City, StateOrProvince, ZIPcode, PhoneNumber, Position, Number, SchoolYear) values ('Trev', 'Leith-Harvey', 'tleithharvey9@wsj.com', '76257 Steensland Street', 'Charlotte', 'North Carolina', '28247', '704-239-1950', 'LW', 68, 'Jr');
insert into Players (FirstName, LastName, Email, StreetAddress, City, StateOrProvince, ZIPcode, PhoneNumber, Position, Number, SchoolYear) values ('Karel', 'McIntosh', 'kmcintosha@apache.org', '1760 Sachtjen Drive', 'Atlanta', 'Georgia', '31119', '770-448-1159', 'RW', 41, 'Jr');
insert into Players (FirstName, LastName, Email, StreetAddress, City, StateOrProvince, ZIPcode, PhoneNumber, Position, Number, SchoolYear) values ('Bruis', 'Logue', 'blogueb@businessweek.com', '08 Memorial Plaza', 'Austin', 'Texas', '78732', '512-370-9203', 'RW', 48, 'Sr');
insert into Players (FirstName, LastName, Email, StreetAddress, City, StateOrProvince, ZIPcode, PhoneNumber, Position, Number, SchoolYear) values ('Alair', 'Kingsmill', 'akingsmillc@linkedin.com', '809 Buell Street', 'Dallas', 'Texas', '75358', '214-633-1377', 'C', 75, 'Fr');
insert into Players (FirstName, LastName, Email, StreetAddress, City, StateOrProvince, ZIPcode, PhoneNumber, Position, Number, SchoolYear) values ('Bevin', 'Officer', 'bofficerd@oracle.com', '5991 Mayfield Alley', 'Washington', 'District of Columbia', '20073', '202-619-5688', 'G', 89, 'Jr');
insert into Players (FirstName, LastName, Email, StreetAddress, City, StateOrProvince, ZIPcode, PhoneNumber, Position, Number, SchoolYear) values ('Raimund', 'Creane', 'rcreanee@cdc.gov', '40 Nelson Avenue', 'Englewood', 'Colorado', '80150', '303-531-5921', 'RW', 84, 'Sr');
insert into Players (FirstName, LastName, Email, StreetAddress, City, StateOrProvince, ZIPcode, PhoneNumber, Position, Number, SchoolYear) values ('Thor', 'Shord', 'tshordf@domainmarket.com', '5965 Ridgeview Alley', 'Cincinnati', 'Ohio', '45238', '513-828-8289', 'D', 42, 'So');
insert into Players (FirstName, LastName, Email, StreetAddress, City, StateOrProvince, ZIPcode, PhoneNumber, Position, Number, SchoolYear) values ('Hubey', 'Dower', 'hdowerg@hc360.com', '078 Eliot Place', 'Seattle', 'Washington', '98133', '206-283-8112', 'C', 43, 'So');
insert into Players (FirstName, LastName, Email, StreetAddress, City, StateOrProvince, ZIPcode, PhoneNumber, Position, Number, SchoolYear) values ('Gradeigh', 'Mongeot', 'gmongeoth@cornell.edu', '64 Cordelia Point', 'Bradenton', 'Florida', '34210', '941-432-0001', 'RW', 59, 'Jr');
insert into Players (FirstName, LastName, Email, StreetAddress, City, StateOrProvince, ZIPcode, PhoneNumber, Position, Number, SchoolYear) values ('Piggy', 'Mullord', 'pmullordi@joomla.org', '94 Carey Trail', 'Newton', 'Massachusetts', '02162', '508-131-7837', 'D', 11, 'Sr');
insert into Players (FirstName, LastName, Email, StreetAddress, City, StateOrProvince, ZIPcode, PhoneNumber, Position, Number, SchoolYear) values ('Carleton', 'Whapple', 'cwhapplej@w3.org', '17188 Lindbergh Avenue', 'Akron', 'Ohio', '44393', '234-811-8115', 'C', 23, 'Jr');
insert into Players (FirstName, LastName, Email, StreetAddress, City, StateOrProvince, ZIPcode, PhoneNumber, Position, Number, SchoolYear) values ('Jay', 'Stealey', 'jstealeyk@upenn.edu', '554 Sommers Terrace', 'Duluth', 'Georgia', '30096', '404-457-0444', 'C', 71, 'Sr');
insert into Players (FirstName, LastName, Email, StreetAddress, City, StateOrProvince, ZIPcode, PhoneNumber, Position, Number, SchoolYear) values ('Bran', 'Manthroppe', 'bmanthroppel@yale.edu', '25 Lakeland Park', 'Johnstown', 'Pennsylvania', '15906', '814-648-1070', 'C', 53, 'Fr');
insert into Players (FirstName, LastName, Email, StreetAddress, City, StateOrProvince, ZIPcode, PhoneNumber, Position, Number, SchoolYear) values ('Jarib', 'Schottli', 'jschottlim@goo.gl', '8129 Monica Place', 'Youngstown', 'Ohio', '44511', '330-110-4827', 'G', 96, 'Sr');
insert into Players (FirstName, LastName, Email, StreetAddress, City, StateOrProvince, ZIPcode, PhoneNumber, Position, Number, SchoolYear) values ('Brit', 'Bilbrook', 'bbilbrookn@hud.gov', '62716 Hanover Terrace', 'Fresno', 'California', '93740', '559-665-3609', 'RW', 15, 'Jr');
insert into Players (FirstName, LastName, Email, StreetAddress, City, StateOrProvince, ZIPcode, PhoneNumber, Position, Number, SchoolYear) values ('Alistair', 'Sutterby', 'asutterbyo@admin.ch', '9 Orin Way', 'Virginia Beach', 'Virginia', '23454', '757-921-3571', 'C', 5, 'So');
insert into Players (FirstName, LastName, Email, StreetAddress, City, StateOrProvince, ZIPcode, PhoneNumber, Position, Number, SchoolYear) values ('Tucker', 'Boot', 'tbootp@etsy.com', '1384 Gerald Alley', 'Sioux Falls', 'South Dakota', '57198', '605-889-2797', 'C', 10, 'Jr');
insert into Players (FirstName, LastName, Email, StreetAddress, City, StateOrProvince, ZIPcode, PhoneNumber, Position, Number, SchoolYear) values ('Ignace', 'Farnell', 'ifarnellq@wikispaces.com', '7747 Lyons Avenue', 'Austin', 'Texas', '78703', '512-591-3811', 'LW', 90, 'Fr');
insert into Players (FirstName, LastName, Email, StreetAddress, City, StateOrProvince, ZIPcode, PhoneNumber, Position, Number, SchoolYear) values ('Theodore', 'Allston', 'tallstonr@sphinn.com', '9 Warrior Terrace', 'Omaha', 'Nebraska', '68117', '402-917-9671', 'RW', 97, 'So');
insert into Players (FirstName, LastName, Email, StreetAddress, City, StateOrProvince, ZIPcode, PhoneNumber, Position, Number, SchoolYear) values ('Rowen', 'Vedenyapin', 'rvedenyapins@geocities.com', '673 Kingsford Road', 'Colorado Springs', 'Colorado', '80940', '719-552-0574', 'D', 75, 'So');
insert into Players (FirstName, LastName, Email, StreetAddress, City, StateOrProvince, ZIPcode, PhoneNumber, Position, Number, SchoolYear) values ('Saxe', 'Artus', 'sartust@sina.com.cn', '004 Village Court', 'Miami', 'Florida', '33158', '305-518-1221', 'RW', 58, 'Sr');
